apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm-service
  template:
    metadata:
      labels:
        app: storm-service
    spec:
      containers:
        - name: storm-service
          image: asia.gcr.io/miloo-phoenix/storm
          ports:
            - containerPort: 5001
            - containerPort: 50051

---

apiVersion: v1
kind: Service
metadata:
  name: storm-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: storm-service
  ports:
    - port: 8020  # REST
      targetPort: 5001
      name: "storm-rest-port"
    - port: 8025  # gRPC
      targetPort: 50051
      name: "storm-grpc-port"
