apiVersion: apps/v1
kind: Deployment
metadata:
  name: storm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storm-service
  template:
    metadata:
      labels:
        app: storm-service
    spec:
      containers:
        - name: storm-service
          image: asia.gcr.io/miloo-phoenix/storm
          ports:
            - containerPort: 5001

---

apiVersion: v1
kind: Service
metadata:
  name: storm-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: storm-service
  ports:
    - port: 8020
      targetPort: 5001
